table Orders
	lineageTag: 2cc37f35-3abb-4288-a4fc-4f5ac0b8f859

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 093ce5b5-ef92-4dc1-bd10-ad98b1367934
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: b5b96f75-7dd1-4c2a-a969-9ace2fb0b8dc
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ad7751c2-7258-42a4-8f17-c3151aac0be8
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 4f34d454-4047-4dc8-9cb2-9ff8c076fc6c
			defaultHierarchy: LocalDateTable_dca259b6-a073-4f49-88f5-05f7e00ad0ed.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3655d610-4e76-47f6-b033-9de47c8d8312
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 002068b3-a0e0-4bf3-8360-756a736237a5
			defaultHierarchy: LocalDateTable_a104617c-0ffe-46d8-a67f-6893472a4eda.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 30fb4b3e-7300-4391-9e7f-79534c833a7e
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 335d8a87-d1dd-4f53-8991-29524af52104
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 5abdf0d2-c733-4950-95a0-e1a7857199b1
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: fa4a10dc-bfc9-406a-9dba-cb329d44cd4d
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 215e0cfc-b2b9-476f-aa31-459dbf523f8c
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7f6c5214-6d1e-4d09-8e56-3babbdb06414
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 8d4a9c59-7548-46e0-8d70-abb44edbd02a
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: b5d7bf3c-46d3-4f83-b3ac-c22117874f8b
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b77f793e-880b-4dcf-acd9-2de459a0b61b
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: b2b6b34c-2175-48f5-b147-a78140e46734
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 806e6196-34f9-4924-974e-6c1028deab10
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 6aad6b32-257e-441d-a6ec-4f1d33b9ef1e
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: db9c8b90-0598-49d3-b0d5-be4653b3f9d1
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 25841ce8-6f55-4b18-8641-d818fc5d44aa
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 1ed838e9-0797-411c-aed8-5fd62d93fc7a
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 85a35da8-0b28-45ef-bf3f-bfe34ab639d3
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 2d5f3810-c40f-4265-9c06-60e8df8e2110
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\AjayDepuri\Downloads\Sample - Superstore 1.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

