table People
	lineageTag: 58b70933-0748-4198-b862-9168e9c35eb9

	column Column1
		dataType: string
		lineageTag: 011be283-d568-41af-8cba-0ac18a2b844b
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 53ed708e-eab0-4548-9d0e-0e53e0e155ea
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition People = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Workflow\Reports\Sample - Superstore_latest.xlsx"), null, true),
				    People_Sheet = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(People_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

