table Superstore_Returns
	lineageTag: db0e19da-786e-4e5e-a8c3-a33fdd5d6987

	column Column1
		dataType: string
		lineageTag: 5546dd55-aede-4ead-8818-db24a9873e70
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 6bbe62b8-799a-4161-bc98-82f50ec3568f
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Superstore_Returns = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Workflow\Reports\Sample - Superstore_latest.xlsx"), null, true),
				    Superstore_Returns_Sheet = Source{[Item="Superstore_Returns",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Superstore_Returns_Sheet,{{"Column1", type text}, {"Column2", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

