table Superstore_Orders
	lineageTag: 85b1f269-6c56-42fc-9e42-cf26616ab25e

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 4b7073fc-7470-4669-8ac0-9fea6164dc61
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 091760ae-b451-4cce-a8ac-977aab5f270f
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2ad81349-083b-48e0-8769-9eddbf356f4e
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 16cff755-5ce2-49c5-ad7b-ac319ed0b7d7
			defaultHierarchy: LocalDateTable_dc9c7340-776e-4351-861d-daf2d55222a5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 545dbeee-5934-4c1a-a85f-c94a643b6643
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: d5d66df5-f642-4a63-b712-6f720555bdd1
			defaultHierarchy: LocalDateTable_df54747f-bee0-40d1-a66a-eb982677e761.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 1240a4c5-2344-4eaa-a3b6-a407444293a4
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 14de9a66-d5a1-450e-8f1a-4ac248f6836e
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: a1b8bdd6-1c85-4552-b67b-031aeedb5101
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 5a8f7f50-5696-4837-bf43-26c931f8741b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 73b09ec6-311f-491a-a328-ca89022bb64d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: b76497a1-6589-4e5e-86ff-ac99f229f377
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6e56c256-a325-4c4d-8d4f-8fe4cdc776a5
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 309f86dd-29b3-4fde-bf46-87d8292365e6
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3d5229ff-54f9-4bac-b0df-b7dc592dbbfb
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 63153a4b-2e45-4d08-a5b6-90d2320c1caf
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ba0057aa-7071-4a75-b588-3cd0a829e9e5
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 74023928-3933-4e53-84c6-365dbd2cf135
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: f5798b5e-d065-4c63-97eb-000203cb277f
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: c64e257a-c791-4eed-94b9-9caa20db1747
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 59f70761-5951-4ff7-9a19-bf04d2d0c0d0
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 3a4b0ff5-7c71-45b7-8d8c-56b35eb8bc24
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: aadd8edf-c93c-4ff5-a6ac-aaa6a4b6c15b
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Superstore_Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Workflow\Reports\Sample - Superstore_latest.xlsx"), null, true),
				    Superstore_Orders_Sheet = Source{[Item="Superstore_Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Superstore_Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

